---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1

steps:
- name: build & push alsa
  image: plugins/docker
  settings:
    repo: ch1ch1/spotifyd
    tag: [ "alsa" ]
    dockerfile: Dockerfile.alsa
    username: ch1ch1
    password:
      from_secret: dockerhub_token
- name: build & push alsa-dbus
  image: plugins/docker
  settings:
    repo: ch1ch1/spotifyd
    tag: [ "alsa-dbus" ]
    dockerfile: Dockerfile.alsa-dbus
    username: ch1ch1
    password:
      from_secret: dockerhub_token
- name: build & push pulseaudio
  image: plugins/docker
  settings:
    repo: ch1ch1/spotifyd
    tag: [ "pulseaudio" ]
    dockerfile: Dockerfile.pulseaudio
    username: ch1ch1
    password:
      from_secret: dockerhub_token
- name: build & push pulseaudio-dbus
  image: plugins/docker
  settings:
    repo: ch1ch1/spotifyd
    tag: [ "pulseaudio-dbus" ]
    dockerfile: Dockerfile.pulseaudio-dbus
    username: ch1ch1
    password:
      from_secret: dockerhub_token
- name: notification success
  image: plugins/webhook
  settings:
    urls:
     from_secret: webhookgotify
    content_type: application/json
    template: |
      {
        "extras": {
        "client::display": {
        "contentType": "text/markdown"
        }
      },
       "message": "![](https://ch1ch1.fr/img/ok.webp) **{{ repo.owner }}** as updated **{{ repo.name }}**, result: **{{ build.status }}**.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [ success ]
- name: notification failure
  image: plugins/webhook
  settings:
    urls:
     from_secret: webhookgotify
    content_type: application/json
    template: |
      {
        "extras": {
        "client::display": {
        "contentType": "text/markdown"
        }
      },
       "message": "![](https://ch1ch1.fr/img/nok.webp) **{{ repo.owner }}** as updated **{{ repo.name }}**, result: **{{ build.status }}**.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [ failure ]

trigger:
  event:
  - push
---
kind: signature
hmac: 61b3e1cce9c1d9aef6f49a34ff274b6b1e1e9b8c557947035b33dd72bff70540

...
