---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1

steps:
- name: build & push alsa-dbus
  image: plugins/docker
  settings:
    repo: ch1ch1/spotifyd
    tag: [ "alsa-dbus" ]
    dockerfile: Dockerfile.alsa-dbus
    username: ch1ch1
    password:
      from_secret: dockerhub_token
- name: notification success
  image: plugins/webhook
  settings:
    urls:
     from_secret: webhookgotify
    content_type: application/json
    template: |
      {
        "extras": {
        "client::display": {
        "contentType": "text/markdown"
        }
      },
       "message": "![](https://ch1ch1.fr/img/ok.webp) **{{ repo.owner }}** as updated **{{ repo.name }}**, result: **{{ build.status }}**.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [ success ]
- name: notification failure
  image: plugins/webhook
  settings:
    urls:
     from_secret: webhookgotify
    content_type: application/json
    template: |
      {
        "extras": {
        "client::display": {
        "contentType": "text/markdown"
        }
      },
       "message": "![](https://ch1ch1.fr/img/nok.webp) **{{ repo.owner }}** as updated **{{ repo.name }}**, result: **{{ build.status }}**.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [ failure ]

trigger:
  event:
  - push
---
kind: signature
hmac: 4be1980e6c930962860601fc1db8a4b60306b528718d1098dea03d4472ac9eb8

...
